# Generated by Django 2.2.7 on 2020-02-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangossl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ssl',
            table='ssl',
        ),
    ]
